
export const ClientDropDown = {
  statusList: ["Active", "Inactive"].slice().sort(),
  clientType: [
    "IT Consultancy",
    "Service Based",
    "Product Based",
    "Others",
  ],
  sourceOfConnection: [
    "LinkedIn",
    "Social Media",
    "Job Portal",
    "Old Student Reference",
    "Reference",
    "Other Reference",
  ],
  sourceOfLocation: [
    "Bangalore",
    "Mumbai",
    "Chandigarh",
    "Hyderabad",
    "Kochi",
    "Pune",
    "Thiruvananthapuram",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Delhi",
    "Other",
  ],
  hrDesignation: [
    "HR",
    "HR Manager",
    "HR Assistant",
    "Recruiter",
    "HR Analyst",
    "Talent Acquisition",
    "Other",
  ],
  callingStatus: [
    "RNR",
    "Busy",
    "Not Reachable",
    "Call Drop",
    "Call you later",
    "No Fresher Hiring",
    "No Openings Currently",
    "Fresher Hiring",
    "Experienced Candidate Hiring",
    "Switch Off",
    "Sent JD",
    "There are no openings on Java",
    "Should check for Freshers hiring",
  ].slice().sort(),
};

